language: cpp

compiler:
  - gcc

install:
  # g++4.8.1
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-get update -qq;
  - sudo apt-get install -qq g++-4.8;
  
  # Arduino lib
  - sudo apt-get install arduino;

script:
  - ls
  - cd quad/
  - make
 
notifications:
  email:
    recipients:
      - romain.goussault@gmail.com
