language: cpp

compiler:
  - gcc

install:
  # Arduino lib
  - sudo apt-get update -qq;
  - sudo apt-get install -qq arduino;

script:
  - ls
  - cd quad/
  - make
 
notifications:
  email:
    recipients:
      - romain.goussault@gmail.com
